### ISSUE TITLE
Use Master Key instead of token

### ISSUE THREAD

**Issue by ghost** [doronnahum/react-parse#8]
I would like to set up my parse with a masterkey in order to have every right on the db? How could I do that ?

**Comment by doronnahum** [comment]
import { config as reactParseConfig, setReactParseDispatch } from 'react-parse'

const apiConfig = { baseURL: envConfig.SERVER_URL, appId: envConfig.PARSE_ID , masterKey: 'YOUR_MASTER_KEY'}

reactParseConfig.init(apiConfig);

**Comment by doronnahum** [comment]
https://github.com/doronnahum/react-parse/issues/8

‫בתאריך יום ג׳, 4 בספט׳ 2018 ב-16:03 מאת ‪youssefmeskini‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by doronnahum** [comment]
@youssefmeskini are you try this?
import { config as reactParseConfig, setReactParseDispatch } from 'react-parse'

const apiConfig = { baseURL: envConfig.SERVER_URL, appId: envConfig.PARSE_ID , masterKey: 'YOUR_MASTER_KEY'}

reactParseConfig.init(apiConfig);
